spring:
  data:
    mongodb:
      uri: "${MONGO_URI}"
      auto-index-creation: true
  redis:
    host: redis
    port: 6379

server:
  port: 8080
  address: 0.0.0.0

aws:
  region: "${AWS_REGION}"
  sqs:
    queue-name: "${SQS_QUEUE_NAME}"
    queue-url: "${SQS_QUEUE_URL}"

cloud:
  aws:
    credentials:
      access-key: "${AWS_ACCESS_KEY_ID}"
      secret-key: "${AWS_SECRET_ACCESS_KEY}"
    region:
      static: "${AWS_REGION}"
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG